// Auto-generated by vite-plugin-auto-routes
import { lazy } from "react";
import type { RouterItem } from "./types";

export const routes: RouterItem[] = [
  {
    path: "/login",
    component: lazy(() => import("../pages/Login")),
    title: "登录",
    meta: {
      title: "登录",
      noAuth: true, // 不需要登录即可访问
    },
  },
  {
    path: "/advisors",
    component: lazy(() => import("../pages/AdvisorList")),
    title: "顾问列表",
    meta: {
      title: "顾问列表",
    },
  },
  {
    path: "/survey",
    component: lazy(() => import("../pages/SurveyForm")),
    title: "问卷调查",
    meta: {
      title: "问卷调查",
    },
  },
  {
    path: "/review",
    component: lazy(() => import("../pages/ReviewManagement")),
    title: "顾问审核管理",
    meta: {
      title: "顾问审核管理",
    },
  },
  {
    path: "/review/detail/:id",
    component: lazy(() => import("../pages/ReviewManagement/DetailPage")),
    title: "审核详情",
    meta: {
      title: "审核详情",
    },
  },
  {
    path: "/theme-demo",
    component: lazy(() => import("../pages/ThemeDemo")),
    title: "主题演示",
    meta: {
      title: "主题演示",
    },
  },
  {
    path: "/dashboard",
    component: lazy(() => import("../pages/Dashboard")),
    title: "仪表板",
    meta: {
      title: "仪表板",
    },
  },
  {
    path: "/customer/:id",
    component: lazy(() => import("../pages/CustomerProfile")),
    title: "客户档案",
    meta: {
      title: "客户档案",
    },
  },
  {
    path: "/contract-order",
    component: lazy(() => import("../pages/ContractOrder")),
    title: "成交报单",
    meta: {
      title: "成交报单",
    },
  },
  {
    path: "/contract-sign/:id",
    component: lazy(() => import("../pages/ContractSign")),
    title: "签署合同",
    meta: {
      title: "签署合同",
    },
  },
  {
    path: "/contract-config",
    component: lazy(() => import("../pages/ContractConfig")),
    title: "合同配置",
    meta: {
      title: "合同配置",
    },
  },
  {
    path: "/recording",
    component: lazy(() => import("../pages/RecordingManagement")),
    title: "录音管理",
    meta: {
      title: "录音管理",
      requiresAuth: true,
    },
  },
  {
    path: "/approval",
    component: lazy(() => import("../pages/ApprovalManagement")),
    title: "审批管理",
    meta: {
      title: "审批管理",
      requiresAuth: true,
    },
  },
  {
    path: "/ceo-dashboard",
    component: lazy(() => import("../pages/CEODashboard")),
    title: "CEO 驾驶舱",
    meta: {
      title: "CEO 驾驶舱",
    },
  },
  {
    path: "/boss",
    component: lazy(() => import("../pages/Boss")),
    title: "老板视图",
    meta: {
      title: "老板视图",
    },
  },
  {
    path: "/market",
    component: lazy(() => import("../pages/Market")),
    title: "市场视图",
    meta: {
      title: "市场视图",
    },
  },
  {
    path: "/goal-setting",
    component: lazy(() => import("../pages/GoalSetting")),
    title: "目标设置",
    meta: {
      title: "目标设置",
    },
  },
  {
    path: "/leads-management",
    component: lazy(() => import("@/pages/LeadsManagement")),
    title: "线索管理",
    meta: {
      title: "线索管理",
    },
  },
];
