import { ItemType } from './types';

export const GOAL_PERIODS = [
  { label: '2026年', value: '2026' },
  { label: '2027年', value: '2027' },
  { label: '2028年', value: '2028' },
];

export const MOCK_TEAM_MEMBERS: ItemType[] = [
  {
    id: 'emp-1',
    name: '张莹',
    group: 'YYDS-张莹',
    tag: '',
    statusColor: '#1890ff',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhangying&backgroundColor=e6f7ff',
    targetAmount: 12000000,
    targetEnrollment: 180,
    targetLeads: 800,
    remark: '',
    tier: 'A',
  },
  {
    id: 'emp-2',
    name: '吴亚丽',
    group: 'YYDS-吴亚丽',
    tag: '',
    statusColor: '#1890ff',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wuyali&backgroundColor=e6f7ff',
    targetAmount: 9109000,
    targetEnrollment: 110,
    targetLeads: 580,
    remark: '',
    tier: 'A',
  },
  {
    id: 'emp-3',
    name: '金雷拉',
    group: 'YYDS-金雷拉',
    tag: '',
    statusColor: '#52c41a',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jinleila&backgroundColor=e6f7ff',
    targetAmount: 10000000,
    targetEnrollment: 145,
    targetLeads: 650,
    remark: '',
    tier: 'B',
  },
  {
    id: 'emp-4',
    name: '王静',
    group: 'YYDS-王静',
    tag: '',
    statusColor: '#1890ff',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wangjing&backgroundColor=e6f7ff',
    targetAmount: 9000000,
    targetEnrollment: 110,
    targetLeads: 580,
    remark: '',
    tier: 'A',
  },
  {
    id: 'emp-5',
    name: '张红吉',
    group: 'YYDS-张红吉',
    tag: '',
    statusColor: '#52c41a',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhanghongji&backgroundColor=e6f7ff',
    targetAmount: 4500000,
    targetEnrollment: 55,
    targetLeads: 420,
    remark: '',
    tier: 'B',
  },
  {
    id: 'emp-6',
    name: '廖正凯',
    group: '优坊-廖正凯',
    tag: '',
    statusColor: '#faad14',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liaozhengkai&backgroundColor=e6f7ff',
    targetAmount: 5000000,
    targetEnrollment: 70,
    targetLeads: 450,
    remark: '',
    tier: 'C',
  },
  {
    id: 'emp-7',
    name: '赵菲菲',
    group: '优坊-赵菲菲',
    tag: '',
    statusColor: '#52c41a',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=zhaofeifei&backgroundColor=e6f7ff',
    targetAmount: 6000000,
    targetEnrollment: 115,
    targetLeads: 500,
    remark: '',
    tier: 'B',
  },
  {
    id: 'emp-8',
    name: '陈孟丽',
    group: '优坊-陈孟丽',
    tag: '',
    statusColor: '#ff4d4f',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chenmengli&backgroundColor=e6f7ff',
    targetAmount: 3000000,
    targetEnrollment: 48,
    targetLeads: 280,
    remark: '',
    tier: 'D',
  },
  {
    id: 'emp-9',
    name: '王璐',
    group: '优坊-王璐',
    tag: '',
    statusColor: '#ff4d4f',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=wanglu&backgroundColor=e6f7ff',
    targetAmount: 3500000,
    targetEnrollment: 50,
    targetLeads: 300,
    remark: '',
    tier: 'D',
  },
  {
    id: 'emp-10',
    name: '刘景',
    group: '优坊-刘景',
    tag: '',
    statusColor: '#ff4d4f',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=liujing&backgroundColor=e6f7ff',
    targetAmount: 2600000,
    targetEnrollment: 50,
    targetLeads: 250,
    remark: '',
    tier: 'D',
  },
];

export const TEAM_STAT_CONFIG = {
  totalGoal: 70000000,
  totalEnrollmentGoal: 1200,
  totalLeadsGoal: 5000,
  lastUpdated: '15:50:10',
};
